%global debug_package %{nil}

Name:		illogical-impulse
Version:	0.0.0
Source0:    illogical-impulse.spec
Release:	1
Summary:	Meta package for Illogical Impulse
URL:		https://github.com/end-4/dots-hyprland
License:	GPL-3.0


Requires:	cava
Requires:	pavucontrol-qt
Requires:	wireplumber
Requires:	libdbusmenu-gtk3
Requires:	playerctl
Requires:	geoclue
Requires:	brightnessctl
Requires:	ddcutil
Requires:	axel
Requires:	bc
Requires:	coreutils
Requires:	cliphist
Requires:	cmake
Requires:	curl
Requires:	rsync
Requires:	wget
Requires:	ripgrep
Requires:	jq
Requires:	meson
Requires:	xdg-user-dirs
Requires:	adw-gtk-theme-git
Requires:	breeze
Requires:	breeze-plus
Requires:	darkly-bin
Requires:	eza
Requires:	fish
Requires:	fontconfig
Requires:	kitty
Requires:	matugen
Requires:	otf-space-grotesk
Requires:	starship
Requires:	ttf-gabarito-git
Requires:	ttf-jetbrains-mono-nerd
Requires:	ttf-material-symbols-variable-git
Requires:	ttf-readex-pro
Requires:	ttf-rubik-vf
Requires:	ttf-twemoji
Requires:	hypridle
Requires:	hyprcursor
Requires:	hyprland
Requires:	hyprland-qtutils
Requires:	hyprland-qt-support
Requires:	hyprlang
Requires:	hyprlock
Requires:	hyprpicker
Requires:	hyprsunset
Requires:	hyprutils
Requires:	hyprwayland-scanner
Requires:	xdg-desktop-portal-hyprland
Requires:	wl-clipboard
Requires:	bluedevil
Requires:	gnome-keyring
Requires:	networkmanager
Requires:	plasma-nm
Requires:	polkit-kde-agent
Requires:	dolphin
Requires:	systemsettings
Requires:	xdg-desktop-portal
Requires:	xdg-desktop-portal-kde
Requires:	xdg-desktop-portal-gtk
Requires:	xdg-desktop-portal-hyprland
Requires:	clang
Requires:	uv
Requires:	gtk4
Requires:	libadwaita
Requires:	libsoup3
Requires:	libportal-gtk4
Requires:	gobject-introspection
Requires:	sassc
Requires:	hyprshot
Requires:	slurp
Requires:	swappy
Requires:	tesseract
Requires:	tesseract-data-eng
Requires:	wf-recorder
Requires:	kdialog
Requires:	qt6-qt5compat
Requires:	qt-avif-image-plugin-qt6
Requires:	qt6-qtbase
Requires:	qt6-qtdeclarative
Requires:	qt6-qtimageformats
Requires:	qt6-qtmultimedia
Requires:	qt6-qtpositioning
Requires:	qt6-qtquicktimeline
Requires:	qt6-qtsensors
Requires:	qt6-qtsvg
Requires:	qt6-qttools
Requires:	qt6-qttranslations
Requires:	qt6-qtvirtualkeyboard
Requires:	qt6-qtwayland
Requires:	syntax-highlighting
Requires:	upower
Requires:	wtype
Requires:	ydotool
Requires:	fuzzel
Requires:	glib2
Requires:	imagemagick
Requires:	hypridle
Requires:	hyprutils
Requires:	hyprlock
Requires:	hyprpicker
Requires:	nm-connection-editor
Requires:	quickshell
Requires:	translate-shell
Requires:	wlogout
Requires:	bibita-cursor-theme

%description
uhh questioning the meaning of dotfiles

%files
